config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_up: 'register', sign_in: 'login', sign_out: 'logout'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
 
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p id="app-footer"><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<div class="container mb-auto">
  <nav class="navbar navbar-expand-lg">
    <%= link_to "Aaron Harrison", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample05">
      <div class="navbar-nav ml-auto">
          <%= nav_helper 'nav-link', 'li'%>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Follow along with my programming journey</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to "Aaron Harrison", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample05">
      <div class="navbar-nav ml-auto">
          <%= nav_helper 'nav-link', 'li'%>
          <%= login_helper 'nav-link' %>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>As a student and an up-and-coming developer, I have created this page to showcase a portion of the skillset I build along the way.</p>
  </div>

  <%= source_helper('alert alert-info blog-sidebar-source') %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Social Links</h4>
    <ul class="list-unstyled social-links">
      <li><a target="_blank" href= "https://github.com/aaronharrison16"><%= fa_icon "github" %></a></li>
      <li><a target="_blank" href= "https://www.linkedin.com/in/aaron-harrison-55a46a155/"  ><%= fa_icon "linkedin" %></a></li>
      <li><a target="_blank" href= "https://www.facebook.com/aaron.harrison.7549"><%= fa_icon "facebook" %></a></li>
      <li><a target="_blank" href= "https://www.instagram.com/aaron.j.harrison/"><%= fa_icon "instagram" %></a></li>
    </ul>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a> /
      <%= link_to "View All Portfolio Items", portfolios_path %>
    </p>

    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Below are a few of the projects to which I have had the opportunity to build, and to contribute.</p>
    <p>
      <%= link_to 'About Me', about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to 'My Blogs', blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Contact me if you have any questions on my skillset, or on my contributions to the listed applications.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <%= login_helper 'text-white' %>  
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <%= link_to "Aaron Harrison", root_path, class: "navbar-brand d-flex align-items-center" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>